import type { Metadata } from "next";
import {Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Suspense } from "react";
import NavLinks from "@/components/NavLinks";
import MarqueePage from "@/components/MarqueePage";


const noto_serif = Noto_Serif_Bengali({
  subsets: ["latin","bengali"],
});


export const metadata: Metadata = {
  title: "Bazar Dor App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${noto_serif.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <div>
       <Header></Header>
        <div className="flex flex-col justify-between relative mx-auto max-w-7xl mt-4">
        <Suspense fallback="loading..">
        <NavLinks></NavLinks>
         <MarqueePage/>
         </Suspense>
         </div>
       </div>
         {children}
        <div>
        <Footer></Footer>
        </div>
      </body>
    </html>
  );
}


